name: Scheduled Workflow

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  scheduled_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run shell script
        run: echo "Hello, GitHub Actions!"
